# Generated by Django 2.2.5 on 2019-11-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
