# Generated by Django 2.2.5 on 2019-11-08 21:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_delete_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='folder',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='manuals.Directory'),
        ),
    ]
