# Generated by Django 2.2.5 on 2019-11-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0005_directory_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='creator',
            new_name='created_by',
        ),
    ]
