# Generated by Django 2.2.5 on 2019-12-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0011_auto_20191227_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='department',
        ),
    ]
