# Generated by Django 2.2.5 on 2019-12-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0012_remove_directory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='manuals.Department'),
        ),
    ]
