# Generated by Django 2.2.5 on 2020-01-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0015_auto_20200103_2200'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='directory_favorites',
            field=models.ManyToManyField(blank=True, related_name='_profile_directory_favorites_+', to='manuals.Directory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manual_favorites',
            field=models.ManyToManyField(blank=True, related_name='_profile_manual_favorites_+', to='manuals.Manual'),
        ),
    ]
